export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const SPROJECT_JSON_REQUEST = 'SPROJECT_JSON_REQUEST';
export const SPROJECT_JSON_SUCCESS = 'SPROJECT_JSON_SUCCESS';
export const SPROJECT_JSON_FAILURE = 'SPROJECT_JSON_FAILURE';
